from django.db import models


# Create your models here.
class Product(models.Model):
    product_id = models.AutoField  # autofield is a integer auto generated by database
    product_name = models.CharField(max_length=100)
    category = models.CharField(max_length=100, default="")
    subcategory = models.CharField(max_length=100, default="")
    price = models.IntegerField(default=0)
    product_description = models.CharField(max_length=800)
    publish_date = models.DateField()
    image = models.ImageField(upload_to="shop/images", default="")

    def __str__(self):
        return self.product_name


class ContactUsMessage(models.Model):
    message_id = models.AutoField(primary_key=True)  # auto field is a integer auto generated by database
    name = models.CharField(max_length=50)
    email = models.CharField(max_length=50, default="")
    phone = models.CharField(max_length=20, default="")
    description = models.CharField(max_length=4000)

    def __str__(self):
        return self.email


class Order(models.Model):
    order_id = models.AutoField(primary_key=True)
    items_JSON = models.CharField(max_length=10000)
    amount = models.IntegerField(default=0)
    delivery = models.CharField(max_length=20, default="Pending")
    paymentStatus = models.CharField(max_length=20, default="Pending")
    name = models.CharField(max_length=80)
    email = models.CharField(max_length=50)
    phone = models.CharField(max_length=50, default=0)
    address = models.CharField(max_length=200)
    city = models.CharField(max_length=100)
    state = models.CharField(max_length=100)
    zip_code = models.CharField(max_length=30)

    def __str__(self):
        return "Order. " + str(self.order_id) + " Payment:" + str(self.paymentStatus) + ", Delivery:" + str(self.delivery)


class OrderUpdate(models.Model):
    update_id = models.AutoField(primary_key=True)
    order_id = models.IntegerField()
    update_description = models.CharField(max_length=5000)
    timeStamp = models.DateField(auto_now_add=True)

    def __str__(self):
        return str(self.order_id) + ". " + self.update_description[0:15] + "..."
