# Generated by Django 3.2 on 2021-04-26 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_order_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderUpdate',
            fields=[
                ('update_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_id', models.IntegerField()),
                ('update_description', models.CharField(max_length=5000)),
                ('timeStamp', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
